name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
  sonarcloud:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet sonarscanner begin \
          /o:etienne-chrp \
          /k:etienne-chrp_dns-tls-proxy \
          /d:sonar.host.url=https://sonarcloud.io
        dotnet build
        dotnet sonarscanner end
